require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('../models/Product');

const connectDB = async () => {
  const uri = process.env.MONGO_URI || process.env.MONGODB_URI;
  if (!uri) {
    console.error('❌ MONGO_URI is missing in environment variables');
    process.exit(1);
  }
  await mongoose.connect(uri);
  console.log('✅ Connected to MongoDB Atlas');
};

const products = [
  // 1. Fruits & Vegetables
  {
    name: 'Fresh Shimla Apples',
    description: 'Crisp, sweet, and juicy Shimla apples sourced directly from Himachal orchards.',
    price: 180,
    originalPrice: 220,
    discount: 18,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?auto=format&fit=crop&w=600&q=80',
    unit: 'kg',
    stock: 75,
    isAvailable: true,
    isFeatured: true,
    isOffer: true,
    isBestSeller: true,
    tags: ['fruit', 'apple', 'fresh', 'shimla', 'organic'],
    brand: 'FreshFarm',
    weight: '1 kg',
    rating: 4.8,
    numReviews: 142,
    reviewCount: 142,
  },
  {
    name: 'Royal Gala Apples',
    description: 'Crispy imported red Gala apples with mild sweet taste.',
    price: 160,
    originalPrice: 190,
    discount: 15,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=600&q=80',
    unit: 'pack',
    stock: 60,
    isAvailable: true,
    tags: ['fruit', 'apple', 'gala', 'imported'],
    brand: 'FreshFarm',
    weight: '4 pcs',
    rating: 4.7,
    numReviews: 95,
    reviewCount: 95,
  },
  {
    name: 'Ripe Robusta Bananas',
    description: 'Naturally ripened Robusta bananas, rich in energy and potassium.',
    price: 60,
    originalPrice: 75,
    discount: 20,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80',
    unit: 'dozen',
    stock: 120,
    isAvailable: true,
    isFeatured: true,
    isBestSeller: true,
    tags: ['fruit', 'banana', 'fresh', 'yellow'],
    brand: 'NatureFresh',
    weight: '12 pieces',
    rating: 4.6,
    numReviews: 98,
    reviewCount: 98,
  },
  {
    name: 'Premium Yelakki Bananas',
    description: 'Sweet fragrant Yelakki mini bananas packed with rich nutrients.',
    price: 55,
    originalPrice: 65,
    discount: 15,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1603833665858-e61d17a86224?auto=format&fit=crop&w=600&q=80',
    unit: 'pack',
    stock: 80,
    isAvailable: true,
    tags: ['fruit', 'banana', 'yelakki', 'fresh'],
    brand: 'NatureFresh',
    weight: '500g',
    rating: 4.8,
    numReviews: 110,
    reviewCount: 110,
  },
  {
    name: 'Juicy Nagpur Oranges',
    description: 'Sun-ripened fresh Nagpur oranges loaded with natural Vitamin C and juice.',
    price: 120,
    originalPrice: 150,
    discount: 20,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?auto=format&fit=crop&w=600&q=80',
    unit: 'kg',
    stock: 80,
    isAvailable: true,
    isFeatured: true,
    tags: ['fruit', 'orange', 'nagpur', 'citrus'],
    brand: 'SunFresh',
    weight: '1 kg',
    rating: 4.7,
    numReviews: 89,
    reviewCount: 89,
  },
  {
    name: 'Premium Alphonso Mangoes',
    description: 'Authentic Ratnagiri Alphonso mangoes. Rich aroma, sweet golden pulp, king of fruits.',
    price: 350,
    originalPrice: 400,
    discount: 12,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?auto=format&fit=crop&w=600&q=80',
    unit: 'dozen',
    stock: 40,
    isAvailable: true,
    isFeatured: true,
    isOffer: true,
    isBestSeller: true,
    tags: ['fruit', 'mango', 'alphonso', 'seasonal'],
    brand: 'RatnagiriFresh',
    weight: '12 pieces',
    rating: 4.9,
    numReviews: 230,
    reviewCount: 230,
  },
  {
    name: 'Sweet Kesar Mangoes',
    description: 'Aromatic sweet Kesar mangoes from Junagadh orchards.',
    price: 240,
    originalPrice: 280,
    discount: 14,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=600&q=80',
    unit: 'kg',
    stock: 50,
    isAvailable: true,
    tags: ['fruit', 'mango', 'kesar', 'sweet'],
    brand: 'FarmFresh',
    weight: '1 kg',
    rating: 4.8,
    numReviews: 165,
    reviewCount: 165,
  },
  {
    name: 'Sweet Black Seedless Grapes',
    description: 'Sweet and crunchy black seedless grapes packed with antioxidants.',
    price: 90,
    originalPrice: 110,
    discount: 18,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?auto=format&fit=crop&w=600&q=80',
    unit: 'pack',
    stock: 60,
    isAvailable: true,
    tags: ['fruit', 'grapes', 'black grapes'],
    brand: 'FreshFarm',
    weight: '500g',
    rating: 4.6,
    numReviews: 64,
    reviewCount: 64,
  },
  {
    name: 'Fresh Green Thomson Grapes',
    description: 'Seedless crisp green grapes, refreshing and sweet.',
    price: 80,
    originalPrice: 95,
    discount: 15,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1596368708356-6e1e1025ee73?auto=format&fit=crop&w=600&q=80',
    unit: 'pack',
    stock: 70,
    isAvailable: true,
    tags: ['fruit', 'grapes', 'green grapes'],
    brand: 'FreshFarm',
    weight: '500g',
    rating: 4.7,
    numReviews: 82,
    reviewCount: 82,
  },
  {
    name: 'Fresh Red Watermelon',
    description: 'Sweet, hydrating, bright red watermelon directly from local farms.',
    price: 110,
    originalPrice: 140,
    discount: 21,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=600&q=80',
    unit: 'piece',
    stock: 35,
    isAvailable: true,
    isOffer: true,
    tags: ['fruit', 'watermelon', 'summer', 'fresh'],
    brand: 'FarmFresh',
    weight: '1 piece (~3kg)',
    rating: 4.5,
    numReviews: 76,
    reviewCount: 76,
  },
  {
    name: 'Ruby Red Pomegranate (Anaar)',
    description: 'Juicy ruby red pomegranate seeds filled with antioxidants and iron.',
    price: 210,
    originalPrice: 250,
    discount: 16,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80',
    unit: 'kg',
    stock: 50,
    isAvailable: true,
    tags: ['fruit', 'pomegranate', 'anaar', 'healthy'],
    brand: 'FreshFarm',
    weight: '1 kg',
    rating: 4.8,
    numReviews: 112,
    reviewCount: 112,
  },
  {
    name: 'Farm Fresh Ripe Papaya',
    description: 'Naturally sweet yellow-orange papaya, excellent for digestion.',
    price: 65,
    originalPrice: 80,
    discount: 18,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1526318896980-cf78c088247c?auto=format&fit=crop&w=600&q=80',
    unit: 'piece',
    stock: 40,
    isAvailable: true,
    tags: ['fruit', 'papaya', 'fresh'],
    brand: 'GreenValley',
    weight: '1 piece (~1kg)',
    rating: 4.4,
    numReviews: 45,
    reviewCount: 45,
  },
  {
    name: 'Sweet Rani Pineapple',
    description: 'Tangy-sweet fresh Rani pineapple packed with digestive enzymes.',
    price: 85,
    originalPrice: 100,
    discount: 15,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?auto=format&fit=crop&w=600&q=80',
    unit: 'piece',
    stock: 30,
    isAvailable: true,
    tags: ['fruit', 'pineapple', 'fresh'],
    brand: 'TropicalFresh',
    weight: '1 piece',
    rating: 4.6,
    numReviews: 53,
    reviewCount: 53,
  },
  {
    name: 'Fresh Green Guava (Amrood)',
    description: 'Crispy green guavas with pink sweet pulp, rich in Vitamin C.',
    price: 75,
    originalPrice: 90,
    discount: 16,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1536511135884-60477e387063?auto=format&fit=crop&w=600&q=80',
    unit: 'kg',
    stock: 45,
    isAvailable: true,
    tags: ['fruit', 'guava', 'amrood'],
    brand: 'GreenValley',
    weight: '1 kg',
    rating: 4.5,
    numReviews: 38,
    reviewCount: 38,
  },
  {
    name: 'Fresh Yellow Lemons (Nimbu)',
    description: 'Juicy, fragrant yellow lemons perfect for lemonade and cooking seasoning.',
    price: 35,
    originalPrice: 45,
    discount: 22,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1534531141161-e41d133a8b50?auto=format&fit=crop&w=600&q=80',
    unit: 'pack',
    stock: 100,
    isAvailable: true,
    tags: ['vegetable', 'lemon', 'nimbu', 'citrus'],
    brand: 'FarmFresh',
    weight: '250g (~6 pcs)',
    rating: 4.3,
    numReviews: 82,
    reviewCount: 82,
  },
  {
    name: 'Vine Ripened Red Tomatoes',
    description: 'Farm-fresh vine tomatoes. Ideal for curries, gravies, and fresh salads.',
    price: 50,
    originalPrice: 60,
    discount: 17,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?auto=format&fit=crop&w=600&q=80',
    unit: 'kg',
    stock: 150,
    isAvailable: true,
    isBestSeller: true,
    tags: ['vegetable', 'tomato', 'fresh', 'red'],
    brand: 'GreenValley',
    weight: '1 kg',
    rating: 4.6,
    numReviews: 195,
    reviewCount: 195,
  },
  {
    name: 'Farm Fresh Hybrid Tomatoes',
    description: 'Firm and juicy hybrid tomatoes for cooking and gravies.',
    price: 28,
    originalPrice: 35,
    discount: 20,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80',
    unit: 'pack',
    stock: 110,
    isAvailable: true,
    tags: ['vegetable', 'tomato', 'hybrid'],
    brand: 'GreenValley',
    weight: '500g',
    rating: 4.5,
    numReviews: 78,
    reviewCount: 78,
  },
  {
    name: 'Fresh Farm Potatoes (Aloo)',
    description: 'High-quality farm potatoes suitable for boiling, frying, and everyday curries.',
    price: 35,
    originalPrice: 45,
    discount: 22,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80',
    unit: 'kg',
    stock: 200,
    isAvailable: true,
    isBestSeller: true,
    tags: ['vegetable', 'potato', 'aloo', 'staple'],
    brand: 'FarmFresh',
    weight: '1 kg',
    rating: 4.7,
    numReviews: 310,
    reviewCount: 310,
  },
  {
    name: 'Organic Baby Potatoes',
    description: 'Small tender baby potatoes ideal for dum aloo.',
    price: 30,
    originalPrice: 40,
    discount: 25,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1508313880080-c4bef0730395?auto=format&fit=crop&w=600&q=80',
    unit: 'pack',
    stock: 90,
    isAvailable: true,
    tags: ['vegetable', 'baby potato', 'aloo'],
    brand: 'FarmFresh',
    weight: '500g',
    rating: 4.6,
    numReviews: 62,
    reviewCount: 62,
  },
  {
    name: 'Fresh Red Onions (Pyaz)',
    description: 'Crisp Indian red onions essential for cooking, tadka, and salads.',
    price: 45,
    originalPrice: 55,
    discount: 18,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=600&q=80',
    unit: 'kg',
    stock: 180,
    isAvailable: true,
    isBestSeller: true,
    tags: ['vegetable', 'onion', 'pyaz', 'staple'],
    brand: 'FarmFresh',
    weight: '1 kg',
    rating: 4.5,
    numReviews: 280,
    reviewCount: 280,
  },
  {
    name: 'Fresh Orange Carrots (Gajar)',
    description: 'Sweet, crunchy orange carrots rich in Beta-Carotene.',
    price: 40,
    originalPrice: 50,
    discount: 20,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=600&q=80',
    unit: 'pack',
    stock: 90,
    isAvailable: true,
    tags: ['vegetable', 'carrot', 'gajar', 'fresh'],
    brand: 'GreenValley',
    weight: '500g',
    rating: 4.6,
    numReviews: 74,
    reviewCount: 74,
  },
  {
    name: 'Crispy Salad Cucumber (Kheera)',
    description: 'Fresh and hydrating salad cucumbers for daily meals.',
    price: 30,
    originalPrice: 40,
    discount: 25,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?auto=format&fit=crop&w=600&q=80',
    unit: 'pack',
    stock: 80,
    isAvailable: true,
    tags: ['vegetable', 'cucumber', 'kheera', 'salad'],
    brand: 'GreenValley',
    weight: '500g',
    rating: 4.4,
    numReviews: 52,
    reviewCount: 52,
  },
  {
    name: 'Tender Purple Brinjal (Baingan)',
    description: 'Fresh purple brinjal suitable for baingan bharta and stuffed curry.',
    price: 35,
    originalPrice: 45,
    discount: 22,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1605335967000-8809e3e70cf2?auto=format&fit=crop&w=600&q=80',
    unit: 'pack',
    stock: 60,
    isAvailable: true,
    tags: ['vegetable', 'brinjal', 'baingan', 'eggplant'],
    brand: 'FarmFresh',
    weight: '500g',
    rating: 4.3,
    numReviews: 39,
    reviewCount: 39,
  },
  {
    name: 'Fresh Lady Finger (Bhindi)',
    description: 'Tender green bhindi directly picked from local farms.',
    price: 45,
    originalPrice: 55,
    discount: 18,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?auto=format&fit=crop&w=600&q=80',
    unit: 'pack',
    stock: 75,
    isAvailable: true,
    tags: ['vegetable', 'bhindi', 'lady finger', 'okra'],
    brand: 'GreenValley',
    weight: '500g',
    rating: 4.5,
    numReviews: 68,
    reviewCount: 68,
  },
  {
    name: 'Vibrant Green Capsicum (Shimla Mirch)',
    description: 'Crispy green capsicum florets for pizza, noodles, and fried rice.',
    price: 35,
    originalPrice: 45,
    discount: 22,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1601001815894-4bb6c828d945?auto=format&fit=crop&w=600&q=80',
    unit: 'pack',
    stock: 85,
    isAvailable: true,
    tags: ['vegetable', 'capsicum', 'shimla mirch'],
    brand: 'GreenValley',
    weight: '250g',
    rating: 4.6,
    numReviews: 83,
    reviewCount: 83,
  },
  {
    name: 'Spicy Green Chillies (Hari Mirch)',
    description: 'Spicy fresh green chillies to add zing to your dishes.',
    price: 15,
    originalPrice: 20,
    discount: 25,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1588610398307-59c40212f458?auto=format&fit=crop&w=600&q=80',
    unit: 'pack',
    stock: 120,
    isAvailable: true,
    tags: ['vegetable', 'chilli', 'green chilli', 'hari mirch'],
    brand: 'FarmFresh',
    weight: '100g',
    rating: 4.7,
    numReviews: 110,
    reviewCount: 110,
  },
  {
    name: 'Fresh Palak Spinach',
    description: 'Organic green spinach leaves packed with iron and vitamins.',
    price: 30,
    originalPrice: 40,
    discount: 25,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=600&q=80',
    unit: 'bunch',
    stock: 90,
    isAvailable: true,
    isOffer: true,
    tags: ['vegetable', 'spinach', 'palak', 'organic'],
    brand: 'GreenValley',
    weight: '250g',
    rating: 4.7,
    numReviews: 95,
    reviewCount: 95,
  },
  {
    name: 'Fresh Green Coriander (Dhaniya)',
    description: 'Aromatic green coriander leaves for garnishing and chutney.',
    price: 15,
    originalPrice: 20,
    discount: 25,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1608797178974-15b35a64ede9?auto=format&fit=crop&w=600&q=80',
    unit: 'bunch',
    stock: 150,
    isAvailable: true,
    tags: ['vegetable', 'coriander', 'dhaniya', 'herb'],
    brand: 'FarmFresh',
    weight: '100g',
    rating: 4.8,
    numReviews: 140,
    reviewCount: 140,
  },
  {
    name: 'Fresh Mint Leaves (Pudina)',
    description: 'Fragrant mint leaves ideal for pudina chutney and drinks.',
    price: 15,
    originalPrice: 20,
    discount: 25,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1628557044797-f21a177c37ec?auto=format&fit=crop&w=600&q=80',
    unit: 'bunch',
    stock: 100,
    isAvailable: true,
    tags: ['vegetable', 'mint', 'pudina', 'herb'],
    brand: 'FarmFresh',
    weight: '100g',
    rating: 4.6,
    numReviews: 87,
    reviewCount: 87,
  },
  {
    name: 'Fresh Ginger (Adrak)',
    description: 'Pungent and juicy fresh ginger root for chai and cooking.',
    price: 45,
    originalPrice: 55,
    discount: 18,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80',
    unit: 'pack',
    stock: 95,
    isAvailable: true,
    tags: ['vegetable', 'ginger', 'adrak', 'spice'],
    brand: 'FarmFresh',
    weight: '250g',
    rating: 4.7,
    numReviews: 115,
    reviewCount: 115,
  },
  {
    name: 'Farm Garlic (Lahsun)',
    description: 'Strong, aromatic garlic pods for rich Indian gravies.',
    price: 60,
    originalPrice: 75,
    discount: 20,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?auto=format&fit=crop&w=600&q=80',
    unit: 'pack',
    stock: 110,
    isAvailable: true,
    tags: ['vegetable', 'garlic', 'lahsun', 'spice'],
    brand: 'FarmFresh',
    weight: '250g',
    rating: 4.6,
    numReviews: 104,
    reviewCount: 104,
  },
  {
    name: 'Sweet Green Peas (Matar)',
    description: 'Fresh tender green peas for matar paneer and pulao.',
    price: 65,
    originalPrice: 80,
    discount: 18,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?auto=format&fit=crop&w=600&q=80',
    unit: 'pack',
    stock: 70,
    isAvailable: true,
    tags: ['vegetable', 'green peas', 'matar'],
    brand: 'GreenValley',
    weight: '500g',
    rating: 4.8,
    numReviews: 92,
    reviewCount: 92,
  },
  {
    name: 'Fresh White Cauliflower (Gobi)',
    description: 'Fresh compact white cauliflower head for aloo gobi.',
    price: 45,
    originalPrice: 55,
    discount: 18,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?auto=format&fit=crop&w=600&q=80',
    unit: 'piece',
    stock: 65,
    isAvailable: true,
    tags: ['vegetable', 'cauliflower', 'gobi'],
    brand: 'GreenValley',
    weight: '1 piece',
    rating: 4.4,
    numReviews: 61,
    reviewCount: 61,
  },
  {
    name: 'Fresh Green Cabbage (Patta Gobi)',
    description: 'Crisp green cabbage for salads, stir fry, and chowmein.',
    price: 35,
    originalPrice: 45,
    discount: 22,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?auto=format&fit=crop&w=600&q=80',
    unit: 'piece',
    stock: 75,
    isAvailable: true,
    tags: ['vegetable', 'cabbage', 'patta gobi'],
    brand: 'GreenValley',
    weight: '1 piece',
    rating: 4.5,
    numReviews: 54,
    reviewCount: 54,
  },
  {
    name: 'Farm Red Beetroot (Chukandar)',
    description: 'Fresh red beetroot loaded with dietary nitrates and iron.',
    price: 30,
    originalPrice: 40,
    discount: 25,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1593105544559-ecb03bf76f82?auto=format&fit=crop&w=600&q=80',
    unit: 'pack',
    stock: 60,
    isAvailable: true,
    tags: ['vegetable', 'beetroot', 'chukandar'],
    brand: 'GreenValley',
    weight: '500g',
    rating: 4.6,
    numReviews: 48,
    reviewCount: 48,
  },
  {
    name: 'Tender Sweet Corn Cobs',
    description: 'Sweet and juicy yellow corn cobs for boiling and roasting.',
    price: 45,
    originalPrice: 55,
    discount: 18,
    category: 'Fruits & Vegetables',
    image: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=600&q=80',
    unit: 'pack',
    stock: 50,
    isAvailable: true,
    tags: ['vegetable', 'sweet corn', 'corn'],
    brand: 'FarmFresh',
    weight: '2 pieces',
    rating: 4.7,
    numReviews: 73,
    reviewCount: 73,
  },

  // 14. Pet Care - FIXING SCREENSHOT DISTINCT IMAGES!
  {
    name: 'Himalaya Erina EP Tick & Flea Shampoo',
    description: 'Herbal anti-tick and flea pet shampoo for dogs and cats.',
    price: 195,
    originalPrice: 225,
    discount: 13,
    category: 'Pet Care',
    image: 'https://images.unsplash.com/photo-1584305574647-0cc949a2bb9f?auto=format&fit=crop&w=600&q=80',
    unit: 'bottle',
    stock: 75,
    isAvailable: true,
    tags: ['pet shampoo', 'himalaya', 'tick shampoo'],
    brand: 'Himalaya',
    weight: '200ml',
    rating: 4.7,
    numReviews: 150,
    reviewCount: 150,
  },
  {
    name: 'Pedigree Dentastix Medium Breed Oral Care Treat',
    description: 'Chew sticks clinically proven to reduce tartar buildup in dogs.',
    price: 185,
    originalPrice: 215,
    discount: 14,
    category: 'Pet Care',
    image: 'https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?auto=format&fit=crop&w=600&q=80',
    unit: 'pack',
    stock: 80,
    isAvailable: true,
    tags: ['dentastix', 'dog treat', 'pedigree'],
    brand: 'Pedigree',
    weight: '180g',
    rating: 4.9,
    numReviews: 210,
    reviewCount: 210,
  },
  {
    name: 'Whiskas Ocean Fish Dry Cat Food',
    description: 'Complete nutritional dry cat food rich in protein & Omega 3.',
    price: 395,
    originalPrice: 460,
    discount: 14,
    category: 'Pet Care',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=600&q=80',
    unit: 'bag',
    stock: 60,
    isAvailable: true,
    tags: ['cat food', 'whiskas', 'ocean fish'],
    brand: 'Whiskas',
    weight: '1.2 kg',
    rating: 4.8,
    numReviews: 190,
    reviewCount: 190,
  },
  {
    name: 'Pedigree Adult Chicken & Vegetables Dog Food',
    description: 'Complete nutritional dry dog food for adult dogs.',
    price: 695,
    originalPrice: 799,
    discount: 13,
    category: 'Pet Care',
    image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=600&q=80',
    unit: 'bag',
    stock: 50,
    isAvailable: true,
    tags: ['pet', 'dog food', 'pedigree', 'pet care'],
    brand: 'Pedigree',
    weight: '3 kg',
    rating: 4.8,
    numReviews: 180,
    reviewCount: 180,
  },
  {
    name: 'Pedigree Adult Chicken Dog Food 1.2kg',
    description: 'Healthy dry dog food pack for small to medium dogs.',
    price: 310,
    originalPrice: 355,
    discount: 12,
    category: 'Pet Care',
    image: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=600&q=80',
    unit: 'bag',
    stock: 70,
    isAvailable: true,
    tags: ['dog food', 'pedigree'],
    brand: 'Pedigree',
    weight: '1.2 kg',
    rating: 4.8,
    numReviews: 140,
    reviewCount: 140,
  },
  {
    name: 'Drools Focus Adult Superpremium Dog Food',
    description: 'Real chicken and rice formula superpremium dog food.',
    price: 799,
    originalPrice: 950,
    discount: 15,
    category: 'Pet Care',
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=600&q=80',
    unit: 'bag',
    stock: 45,
    isAvailable: true,
    tags: ['drools', 'dog food', 'superpremium'],
    brand: 'Drools',
    weight: '3 kg',
    rating: 4.8,
    numReviews: 160,
    reviewCount: 160,
  },
];

const seedDB = async () => {
  try {
    await connectDB();

    let inserted = 0;
    let updated = 0;

    for (const item of products) {
      const existing = await Product.findOne({ name: item.name });
      if (existing) {
        await Product.updateOne({ _id: existing._id }, item);
        updated++;
      } else {
        await Product.create(item);
        inserted++;
      }
    }

    const totalCount = await Product.countDocuments();
    console.log(`✅ Seed Operation Summary:`);
    console.log(`   - New products inserted: ${inserted}`);
    console.log(`   - Existing products updated: ${updated}`);
    console.log(`   - Total products in database: ${totalCount}`);

    mongoose.connection.close();
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed error:', error.message);
    process.exit(1);
  }
};

seedDB();
